### ISSUE TITLE
Better to support comma-space-separator in IncludeDirective

### ISSUE THREAD

**Issue by zhouqing86** [jsonapi-rb/jsonapi-renderer#18]
It would be great  if JSONAPI::IncludeDirective support comma-space-separator String.

```
JSONAPI::IncludeDirective.new("friends, comments, posts")
```

Developers usually add space after comma.

**Comment by beauby** [comment]
@zhouqing86 Thanks for opening this issue. As I said in #16, I am against this. However, for developer-specified include lists, you can use the following syntax:
```ruby
JSONAPI::IncludeDirective.new([:friends, :comments, :posts])
```

**Comment by zhouqing86** [comment]
Thanks @beauby for your quick response!

I originally submit an issue on active_model_serializers which are using jsonapi-renderer. rails-api/active_model_serializers#2139

I am agree with your concern that we need to follow JSON API spec. Thanks again.

I will close this ticket!
