### ISSUE TITLE
if fields is nil, there is an error.

### ISSUE THREAD

**Issue by NullVoxPopuli** [jsonapi-rb/jsonapi-renderer#20]
is this intentional?
![2017-06-23-082158_458x110_scrot](https://user-images.githubusercontent.com/199018/27481881-0b50fee0-57ed-11e7-95a5-f81d93a60bae.png)
above is the workaround.

without I get the error:
```
       undefined method `each_with_object' for nil:NilClass
```

**Comment by beauby** [comment]
Not sure I'm understanding the situation. The `fields` option can be either not supplied, or a hash of arrays of symbols. Could you provide a full stack trace along with the faulty code?

**Comment by NullVoxPopuli** [comment]
yup, here is a trace:
```
  Failure/Error:
           # the json assignment is line 12
           json = JSONAPI::Serializable::Renderer.render(
             data,
             include: params[:include],
             fields: params[:fields],
             class: SerializableUser
       
           )
     
     NoMethodError:
       undefined method `each_with_object' for nil:NilClass
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-renderer-0.1.2/lib/jsonapi/renderer/document.rb:53:in `_symbolize_fields'
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-renderer-0.1.2/lib/jsonapi/renderer/document.rb:12:in `initialize'
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-renderer-0.1.2/lib/jsonapi/renderer.rb:23:in `new'
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-renderer-0.1.2/lib/jsonapi/renderer.rb:23:in `render'
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-serializable-0.1.3/lib/jsonapi/serializable/renderer.rb:24:in `render'
     # /home/lprestonsegoiii/.gem/ruby/2.4.0/gems/jsonapi-serializable-0.1.3/lib/jsonapi/serializable/renderer.rb:8:in `render'
     # ./app/controllers/concerns/jsonapi_endpoints.rb:12:in `render_data'
```

I'm manually invoking `jsonapi-rb`, just for fun for some benchmarks of various scenarios -- so it's totally possible I messed something up.

Here is the calling code's context if you're curious: https://github.com/NullVoxPopuli/rails-NPlusOneTests/blob/master/app/controllers/concerns/jsonapi_endpoints.rb#L12

**Comment by beauby** [comment]
Right, so what's happening is that `params.fetch(:fields, {})` will result in `nil` if `params[:fields]` is explicitly set to `nil`. I'd accept a PR to fix that (basically replacing the `params.fetch(:fields, {})` in [this line](https://github.com/jsonapi-rb/jsonapi-renderer/blob/master/lib/jsonapi/renderer/document.rb#L12) with `params[:fields] || {}`.

**Comment by NullVoxPopuli** [comment]
NOICE, @beauby
