### ISSUE TITLE
JSONAPI::IncludeDirective::InvalidKey raised when includes underscore

### ISSUE THREAD

**Issue by SirRawlins** [jsonapi-rb/jsonapi-renderer#37]
Good morning folks. 👋 

Just bumped to `0.2.1` which includes #36. I have now started receiving `JSONAPI::IncludeDirective::InvalidKey` errors for keys which include (but don't begin or end with) an underscore.

[Reading the specification](https://jsonapi.org/format/#document-member-names-allowed-characters) it suggests that underscores are allowed, so long as they're not at the beginning or end?

I'm horrible at working with REGEX so putting together a fix is a bit outside of my ability, otherwise, I'd put together a PR.

**Comment by InteNs** [comment]
I'm having the same issue

**Comment by Japestrale** [comment]
I'm also experiencing this

**Comment by d--j** [comment]
This regular expression should work `/^(?![ \-_])[\u0080-\u10FFFFA-Za-z0-9_ -]+(?<![ \-_])$/` . 
(added `-`, `_` and ` ` (space) as valid characters, removed `*` since it is not [valid](https://jsonapi.org/format/#document-member-names))


Test here: https://rubular.com/r/s5bUXhkj2gpGzl

**Comment by jonmast** [comment]
I've opened a PR with a fix: #38 

Fix is similar to @d--j's suggestion but keeps the star in, while it is not valid in key names it's used as a wildcard in includes.

**Comment by nesrual** [comment]
Same problem here - reverting to 0.2.0 solves the problem

**Comment by mihairadulescu** [comment]
same issue here ..
![image](https://user-images.githubusercontent.com/11047826/59432617-6bb1e980-8df0-11e9-838f-930226b11636.png)

**Comment by beauby** [comment]
@dawidof This needs attention when you get a chance
